# Generated by Django 5.2.11 on 2026-02-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('qr_code', models.CharField(max_length=50, unique=True, verbose_name='Código QR')),
                ('current_streak', models.IntegerField(default=0, verbose_name='Racha Actual')),
                ('last_checkin', models.DateField(blank=True, null=True, verbose_name='Última Visita')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
