# Generated by Django 5.2.11 on 2026-02-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='mensuality_date',
            field=models.DateField(blank=True, null=True, verbose_name='Mensualidad'),
        ),
    ]
