# Generated by Django 5.2.11 on 2026-02-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_member_mensuality_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streaks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameStreak', models.CharField(max_length=100, verbose_name='Nombre Racha')),
                ('daysStreak', models.CharField(max_length=100, verbose_name='Dias totales')),
            ],
        ),
    ]
