# Generated by Django 5.2.11 on 2026-02-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_streaks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streaks',
            name='nameStreak',
            field=models.IntegerField(default=0, verbose_name='Nombre Racha'),
        ),
    ]
