# Generated by Django 5.2.11 on 2026-02-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_streaks_namestreak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streaks',
            name='daysStreak',
            field=models.IntegerField(default=0, verbose_name='Dias totales'),
        ),
        migrations.AlterField(
            model_name='streaks',
            name='nameStreak',
            field=models.CharField(max_length=100, verbose_name='Nombre Racha'),
        ),
    ]
