# Generated by Django 5.2.11 on 2026-02-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_streaks_daysstreak_alter_streaks_namestreak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='last_checkin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Visita'),
        ),
    ]
