# Generated by Django 5.2.11 on 2026-02-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_member_last_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='mexpirate_date',
            field=models.DateField(blank=True, null=True, verbose_name='Nueva Mensualidad'),
        ),
    ]
