# Generated by Django 5.2.11 on 2026-02-19 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_member_mexpirate_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='mexpirate_date',
        ),
    ]
