# Generated by Django 5.2.11 on 2026-03-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_member_mexpirate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_mensuality_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ultima Mensualidad'),
        ),
    ]
