# Generated by Django 5.2.11 on 2026-03-16 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_member_last_mensuality_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='last_mensuality_date',
        ),
    ]
